name: eztransport
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.17.5 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get_it: ^7.1.3
  connectivity_plus: ^2.2.0
  dio: ^4.0.0
  flutter_screenutil: ^5.0.0
  get: ^4.1.4
  intl: ^0.17.0
  shimmer: ^2.0.0
  shared_preferences: ^2.0.5
  provider: ^6.0.3
  permission_handler: ^9.0.2
  logger: ^1.0.0
  url_launcher: ^6.0.7
  expansion_widget: ^0.0.3
  flutter_mapbox_navigation: 0.0.26
  geolocator: ^8.0.1
  geocoding: ^2.0.5
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
